services:
  server:
    build: ./server
    networks:
      - zmq_net
    ports:
      - "5510:5510"
  client:
    build: ./client
    networks:
      - zmq_net
    ports:
      - "8080:8080"
    depends_on:
      - server

networks:
  zmq_net:
    driver: bridge